image: docker:24.0.5

services:
  - docker:24.0.5-dind

stages:
  - build
  - test
  - pack  # 只有前兩關過了，才執行這關

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

# 第一關：純編譯檢查
compile_job:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:9.0
  script:
    - dotnet build MyAPI.sln

# 第二關：自動跑測試
unit_test_job:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:9.0
  script:
    - dotnet test MyAPI.sln --no-build

# 第三關：測試過關才打包 Image
docker_build_job:
  stage: pack
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG